# Generated by Django 5.1 on 2024-11-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
