# Generated by Django 5.1 on 2024-11-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_creditcard_my_integer_alter_creditcard_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='my_integer',
        ),
    ]
